language: python
sudo: false

env:
  - LUA="lua=5.1"
  - LUA="lua=5.2"
  - LUA="lua=5.3"
  - LUA="luajit=2.0"
  - LUA="luajit=2.1"

before_install:
  - pip install hererocks
  - hererocks lua_install --$LUA -rlatest
  - source env/bin/activate

install:
  - luarocks make

script:
  - lua test.lua

branches:
  except:
    - gh-pages

notifications:
  email:
    on_success: change
    on_failure: always